from PySide6.QtCore import QMetaObject, QSize
from PySide6.QtGui import Qt
from PySide6.QtWidgets import (QDockWidget, QWidget, QSizePolicy, QSlider, QPushButton,
                               QAbstractItemView, QListView, QListWidget, QVBoxLayout)


class Thumbnails(QDockWidget):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.objectName():
            self.setObjectName(u"thumbnails")
        self.setWindowModality(Qt.WindowModal)
        #self.resize(759, 544)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setBaseSize(QSize(800, 680))
        self.verticalLayout = QVBoxLayout(self)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        #self.dockWidget = QDockWidget(self)
        #self.dockWidget.setObjectName(u"dockWidget")
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        #self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.thumbs = QListWidget(self.dockWidgetContents)
        self.thumbs.setObjectName(u"thumbs")
        sizePolicy.setHeightForWidth(self.thumbs.sizePolicy().hasHeightForWidth())
        self.thumbs.setSizePolicy(sizePolicy)
        self.thumbs.setBaseSize(QSize(800, 680))
        self.thumbs.setFocusPolicy(Qt.NoFocus)
        #self.thumbs.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.thumbs.setAcceptDrops(False)
        self.thumbs.setToolTip(u"")
        self.thumbs.setAccessibleName(u"")
        self.thumbs.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.thumbs.setProperty("showDropIndicator", False)
        self.thumbs.setDragEnabled(False)
        self.thumbs.setDragDropMode(QAbstractItemView.NoDragDrop)
        self.thumbs.setDefaultDropAction(Qt.IgnoreAction)
        self.thumbs.setIconSize(QSize(150, 150))
        self.thumbs.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.thumbs.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.thumbs.setMovement(QListView.Free)
        self.thumbs.setResizeMode(QListView.Adjust)
        self.thumbs.setLayoutMode(QListView.Batched)
        self.thumbs.setGridSize(QSize(150, 200))
        self.thumbs.setViewMode(QListView.IconMode)
        self.thumbs.setUniformItemSizes(True)
        self.thumbs.setWordWrap(True)
        self.thumbs.setSelectionRectVisible(False)
        self.thumbs.setSortingEnabled(False)
        self.verticalLayout_2.addWidget(self.thumbs)

        self.refresh = QPushButton(self.dockWidgetContents)
        self.refresh.setObjectName(u"refresh")

        self.verticalLayout_2.addWidget(self.refresh)

        self.thumbsZoom = QSlider(self.dockWidgetContents)
        self.thumbsZoom.setObjectName(u"thumbsZoom")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.thumbsZoom.sizePolicy().hasHeightForWidth())
        self.thumbsZoom.setSizePolicy(sizePolicy1)
        self.thumbsZoom.setMinimumSize(QSize(0, 15))
        self.thumbsZoom.setMinimum(5)
        self.thumbsZoom.setMaximum(512)
        self.thumbsZoom.setValue(150)
        self.thumbsZoom.setOrientation(Qt.Horizontal)

        self.verticalLayout_2.addWidget(self.thumbsZoom)

        self.setWidget(self.dockWidgetContents)

        self.verticalLayout.addWidget(self)


        QMetaObject.connectSlotsByName(self)
