name: ai-nodes
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip 22.2.2
  - cudatoolkit=11.3
  - pytorch=1.13.0
  - torchvision=0.14.0
  - numpy=1.23.1
  - pip:
        - PySide6
